### PR TITLE
Integer dataTypes

### PR DESCRIPTION
**Pull request by srihari201**
Hi Hari,

I am raising PR for "Integer dataTypes" please review it and lemme know if there are any changes are required.

Thanks,
Srihari A

### CODE REVIEW

**Comment by sradada** [comment]
Hi Srihari,

I have reviewed your PR, and everything looks good. However, could you please add comments indicating the size of the respective data types? This will help everyone understand the details more easily.

Thanks,
Hari A

**Comment by srihari201** [comment]
Hi Hari,

As discussed Added size of the Integer Data Types and raising the new PR. Please check it and lemme know.

Thanks,
Srihari A

**Comment by sradada** [comment]
Hi Srihari, 
Everything looks good 😊. So approving the PR.
Thanks, 
srihari A

**Review by sradada — COMMENTED** [review]
Good 😊

**Review by sradada — APPROVED** [review]

**Pull request merged**
